#!/bin/sh
# 预置防火墙放行规则：PT 51413 + lucky 7999
# 首次开机自动执行

# PT 下载端口（TCP+UDP，目标地址留空适配 v6 前缀变化）
uci -q delete firewall.pt_51413
uci set firewall.pt_51413='rule'
uci set firewall.pt_51413.name='PT-51413'
uci set firewall.pt_51413.src='wan'
uci set firewall.pt_51413.dest='lan'
uci set firewall.pt_51413.proto='tcp udp'
uci set firewall.pt_51413.dest_port='51413'
uci set firewall.pt_51413.target='ACCEPT'

# lucky 反代端口（TCP）
uci -q delete firewall.lucky_7999
uci set firewall.lucky_7999='rule'
uci set firewall.lucky_7999.name='Lucky-7999'
uci set firewall.lucky_7999.src='wan'
uci set firewall.lucky_7999.dest='lan'
uci set firewall.lucky_7999.proto='tcp'
uci set firewall.lucky_7999.dest_port='7999'
uci set firewall.lucky_7999.target='ACCEPT'

uci commit firewall
exit 0
